# Cloudflare Worker Configuration for AI Coaching API
name = "ai-coaching-api"
main = "src/index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# Worker settings
workers_dev = true
send_metrics = true

# Environment configurations
[env.production]
name = "ai-coaching-api-prod"
route = { pattern = "api.yourapp.com/*", zone_name = "yourapp.com" }

[env.staging]
name = "ai-coaching-api-staging"

# KV Namespaces for data storage
[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "your-rate-limit-kv-id"
preview_id = "your-rate-limit-kv-preview-id"

[[kv_namespaces]]
binding = "USER_SESSIONS_KV"
id = "your-user-sessions-kv-id"
preview_id = "your-user-sessions-kv-preview-id"

[[kv_namespaces]]
binding = "COACHING_HISTORY_KV"
id = "your-coaching-history-kv-id"
preview_id = "your-coaching-history-kv-preview-id"

# D1 Database (optional - for advanced data storage)
# [[d1_databases]]
# binding = "DB"
# database_name = "coaching-database"
# database_id = "your-d1-database-id"

# Environment variables (non-sensitive)
[vars]
ENVIRONMENT = "development"
API_VERSION = "2.0.0"

# Build configuration
[build]
command = "npm run build"

# Triggers for scheduled events (optional)
[triggers]
crons = ["0 2 * * *"]  # Daily at 2 AM UTC for cleanup tasks

# Analytics and monitoring
[observability]
enabled = true

# Durable Objects (for future session management)
# [[durable_objects.bindings]]
# name = "COACHING_SESSION"
# class_name = "CoachingSession"

# Worker limits and performance
[limits]
cpu_ms = 10000  # 10 seconds max CPU time