# Cloudflare Worker Configuration
# Configure your worker deployment settings

name = "coaching-api-worker"
main = "src/index.js"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# Worker configuration
workers_dev = true

# Environment variables (set these in Cloudflare dashboard or via wrangler secrets)
[env.production]
name = "coaching-api-worker-prod"
route = "api.yourapp.com/*"

[env.staging]
name = "coaching-api-worker-staging"

# KV Namespaces for rate limiting and caching
[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "your-kv-namespace-id"

# Environment variables (non-sensitive)
[vars]
ENVIRONMENT = "production"
API_VERSION = "1.0.0"

# Triggers for scheduled events
[triggers]
crons = ["0 0 * * *"]  # Daily at midnight UTC

# Build configuration
[build]
command = ""