name = "ai-coaching-api"
main = "src/index.ts"
compatibility_date = "2024-03-20"
nodejs_compat = true

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "locus-user-data"
database_id = "8860a9a3-2116-4a80-b836-5f668c1a1d68"

[[vectorize]]
binding = "VECTORIZE_INDEX"
index_name = "user-journal-embeddings"

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "90eb674e2bf84eab813edbacfff6f120"

[[kv_namespaces]]
binding = "USER_SESSIONS_KV"
id = "26f231f76b0949eb82a76d4f7c413d33"

[[kv_namespaces]]
binding = "COACHING_HISTORY_KV"
id = "5845c2885c654de88998bb1e795c08a7"